### ISSUE TITLE
trying to use cryofold 2 - "RuntimeError: Unknown scaler type "linear_blur" 

### ISSUE THREAD

**Issue by yoavatsmonraz** [maccallumlab/meld#147]
Thank you very much for writing this code, I've been trying to get it to work with a cryo map that i have but so far it hasn't been working so well. Apparently, it fails identifying the linear_blur scaler that is defined in the new cryofold setup script. I've installed meld from conda and got this error and then I tried setting it up from scratch and it still gave the same error so I'm not really sure what I'm missing here. Specifically, I'm getting this error:

home/yoava/anaconda3/envs/meld/lib/python3.9/site-packages/openmm/app/internal/amber_file_parser.py:1102: UserWarning: Non-optimal GB parameters detected for GB model GBn2
  warnings.warn(
Traceback (most recent call last):
  File "/home/yoava/anaconda3/envs/meld/lib/python3.9/site-packages/meld/system/scalers.py", line 45, in get_constructor_for_key
    return ScalerRegistry._scaler_registry[key]
KeyError: 'linear_blur'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yoava/software/meld/docs/tutorial/cryofold_tutorial/setup_cryofold.py", line 106, in <module>
    setup_system()
  File "/home/yoava/software/meld/docs/tutorial/cryofold_tutorial/setup_cryofold.py", line 55, in setup_system
    blur_scaler = s.restraints.create_scaler(
  File "/home/yoava/anaconda3/envs/meld/lib/python3.9/site-packages/meld/system/restraints.py", line 1492, in create_scaler
    return ScalerRegistry.get_constructor_for_key(scaler_type)(**kwargs)
  File "/home/yoava/anaconda3/envs/meld/lib/python3.9/site-packages/meld/system/scalers.py", line 47, in get_constructor_for_key
    raise RuntimeError(f'Unknown scaler type "{key}".')
RuntimeError: Unknown scaler type "linear_blur"

-------------

Thanks in advance for any help you can provide with this,

**Comment by yoavatsmonraz** [comment]
EDIT: Apologies, apparently it had to do with a bad conda env setup. Nevertheless, now I'm getting issues with the plugin installation (it can't seem to find openMM) but the original issue is closed.

**Comment by yoavatsmonraz** [comment]
Closed
