### ISSUE TITLE
error while running launch_remd

### ISSUE THREAD

**Issue by yoavatsmonraz** [maccallumlab/meld#149]
I've been trying to run launch_remd on an aws cloud machine as described in the cryofold tutorial but i keep getting this error:
loading data store
initializing communicator
Traceback (most recent call last):
  File ".../launch_remd", line 34, in <module>
    main()
  File ".../launch_remd", line 29, in main
    launch.launch(args.platform, console, args.debug, args.console_log)
  File ".../anaconda3/envs/meld/lib/python3.10/site-packages/meld/remd/launch.py", line 101, in launch
    system = store.load_system()
  File ".../anaconda3/envs/meld/lib/python3.10/site-packages/meld/vault.py", line 881, in load_system
    return _load_pickle(system_file)
  File "/.../anaconda3/envs/meld/lib/python3.10/site-packages/meld/vault.py", line 38, in _load_pickle
    return pickle.load(data)
AttributeError: Can't get attribute 'DensityRestraint' on <module 'meld.system.restraints' from '.../anaconda3/envs/meld/lib/python3.10/site-packages/meld/system/restraints.py'>
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------

The current meld and meldplugin versions are 0.6.1 and seem to be correctly compiled. Any assistance will be much appreciated,
thanks in advance

**Comment by ccccclw** [comment]
It looks like MELD was installed from conda-forge. We haven't updated the latest change to conda package, so the DensityRestraint feature is not included. Do you think we will release a new version in the near future? @jlmaccal

**Comment by yoavatsmonraz** [comment]
@ccccclw  is their any other way to currently use the updated code ?

**Comment by ccccclw** [comment]
Yes, you can build from source following the guidance here `https://github.com/maccallumlab/meld#building-from-scratch`

**Comment by yoavatsmonraz** [comment]
I've actually followed the instruction as described, launched script for the new build's scripts dir and I got exactly the same error. Would it be possible to update the new code for density restraint into conda as an alternative ?

**Comment by kvr2007** [comment]
> @ccccclw I've actually followed the instruction as described, launched script for the new build's scripts dir and I got exactly the same error. Would it be possible to update the new code for density restraint into conda as an alternative ?

I managed to package MELD from source, it's not straightforward, but doable ;)

I have attached the package lists for conda and pip. You can use those to create a dedicated conda environment.

[packages_conda.txt](https://github.com/maccallumlab/meld/files/11834670/packages_conda.txt)
[packages_pip.txt](https://github.com/maccallumlab/meld/files/11834671/packages_pip.txt)

Once the environment is set up, you need to compile `meldplugin`. This requires that you have CUDA available (e.g. loaded from a module if you are working on a cluster). This is what needs to run in the folder with the current snapshot of MELD git repo:

```
rm -rf ./plugin/build
mkdir -p ./plugin/build
cd ./plugin/build
cmake --log-level STATUS \
-DCMAKE_INSTALL_PREFIX=${CONDA_PREFIX} \
-DOPENMM_DIR=${CONDA_PREFIX} \
-DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-11 \
-DEXTRA_COMPILE_FLAGS="-L/usr/local/cuda-11/lib64/stubs -Wl,-rpath,/usr/local/cuda-11/lib64/stubs -Wl,-rpath-link,/usr/local/cuda-11/lib64/stubs" \
..
make -j $SLURM_CPUS_PER_TASK install
make PythonInstall
cd python
pip install .
```

Finally, you need to install the python package for MELD, which is also done from within the git snapshot:

`pip install .`
