### ISSUE TITLE
'RunOptions' object has no attribute 'solvation' when using extract_traj_dcd

### ISSUE THREAD

**Issue by atbogetti** [maccallumlab/meld#153]
Hello,

I am running the MELD tutorial with alanine dipeptide in implicit solvent, but when I go to extract my trajectories with:

`extract_trajectory extract_traj_dcd --replica 0 test.dcd`

I get the error

> Traceback (most recent call last):                                                                                                                                                             
  File "/home/anthony/apps/anaconda3/envs/meld/bin/extract_trajectory", line 366, in <module>                                                                                                  
    main()                                                                                                                                                                                     
  File "/home/anthony/apps/anaconda3/envs/meld/bin/extract_trajectory", line 126, in main                                                                                                      
    args.func(store, args)                                                                                                                                                                     
  File "/home/anthony/apps/anaconda3/envs/meld/bin/extract_trajectory", line 168, in extract_traj_dcd                                                                                          
    if store.load_run_options().solvation:                                                                                                                                                     
AttributeError: 'RunOptions' object has no attribute 'solvation' 

I used the `meld.setup_data_store(system, options, remd)` line in my setup script and the MELD simulation ran as expected. Should I be including more lines to store this data?

Thank you,
Anthony

**Comment by splenz** [comment]
Hi Anthony,

You might be using an old version of the extract trajectory script. Can you update MELD to see if the issue persists? In particular, commit 2db6648 solved this issue by retrieving solvation from the system object instead of the RunOptions object.

Please let me know if the issue persists after updating. 

Stefan
