### ISSUE TITLE
error: identifier "MAXFLOAT" is undefined when running MELD 0.6.1 on GPUs w/ restraints

### ISSUE THREAD

**Issue by atbogetti** [maccallumlab/meld#154]
Hello again,

I have been trying to run MELD 0.6.1 on GPUs and keep getting this error:

> Traceback (most recent call last):
  File "/titan/anthony/apps/miniconda3/envs/meld0.6.1/bin/launch_remd", line 34, in <module>
    main()
  File "/titan/anthony/apps/miniconda3/envs/meld0.6.1/bin/launch_remd", line 29, in main
    launch.launch(args.platform, console, args.debug, args.console_log)
  File "/titan/anthony/apps/miniconda3/envs/meld0.6.1/lib/python3.10/site-packages/meld/remd/launch.py", line 111, in launch
    remd_runner.run(communicator, system_runner, store)
  File "/titan/anthony/apps/miniconda3/envs/meld0.6.1/lib/python3.10/site-packages/meld/remd/leader.py", line 120, in run
    system_runner.prepare_for_timestep(my_state, 0.0, self._step)
  File "/titan/anthony/apps/miniconda3/envs/meld0.6.1/lib/python3.10/site-packages/meld/runner/openmm_runner.py", line 104, in prepare_for_timestep
    self._initialize_simulation(state)
  File "/titan/anthony/apps/miniconda3/envs/meld0.6.1/lib/python3.10/site-packages/meld/runner/openmm_runner.py", line 293, in _initialize_simulation
    self._simulation = _create_openmm_simulation(
  File "/titan/anthony/apps/miniconda3/envs/meld0.6.1/lib/python3.10/site-packages/meld/runner/openmm_runner.py", line 611, in _create_openmm_simulation
    return app.Simulation(topology, system, integrator, platform, properties)
  File "/titan/anthony/apps/miniconda3/envs/meld0.6.1/lib/python3.10/site-packages/openmm/app/simulation.py", line 103, in __init__
    self.context = mm.Context(self.system, self.integrator, platform, platformProperties)
  File "/titan/anthony/apps/miniconda3/envs/meld0.6.1/lib/python3.10/site-packages/openmm/openmm.py", line 12378, in __init__
    _openmm.Context_swiginit(self, _openmm.new_Context(*args))
openmm.OpenMMException: Error launching CUDA compiler: 256

> /local/430750.1.gpu_long_2080ti/openmmTempKernel0x555556f7a5a0_122599.cu(1312): error: identifier "MAXFLOAT" is undefined

> /local/430750.1.gpu_long_2080ti/openmmTempKernel0x555556f7a5a0_122599.cu(1334): warning: type qualifier is meaningless on cast type

> /local/430750.1.gpu_long_2080ti/openmmTempKernel0x555556f7a5a0_122599.cu(1398): error: identifier "MAXFLOAT" is undefined

> /local/430750.1.gpu_long_2080ti/openmmTempKernel0x555556f7a5a0_122599.cu(1420): warning: type qualifier is meaningless on cast type

> 2 errors detected in the compilation of "/local/430750.1.gpu_long_2080ti/openmmTempKernel0x555556f7a5a0_122599.cu".

I've tried a lot of different things (cuda toolkit versions, gcc versions etc) but nothing helps. Any idea what could be causing this?

Some more context. With the same installation, I can run on CPUs just fine. Also, if I run MELD without any restraints, it will also run fine on the GPUs. It's only the combination of restraints and GPUs that leads to this error.

Anthony

**Comment by atbogetti** [comment]
Installing as described here with the latest version fixed it for me: https://github.com/maccallumlab/meld/issues/149

**Comment by Wujiazhang** [comment]
Hello, I have the same problem, do you solve it?
