### ISSUE TITLE
MELD-DNA

### ISSUE THREAD

**Issue by stianale** [maccallumlab/meld#161]
Hi,

This looks like a very good software. However, I have no clue how to run it, much less MELD-DNA. The documentation that exists seems very intricate and not easily reproducible, and I find no walkthrough, examples etc. on how to use MELD-DNA. I cloned this repo and downloaded the Zenodo zip file in the same directory. After having installed MELD using conda-forge, and following the walkthrough on how to install mpi4py. I guessed trying `python setupMELD.py` would be a start but get this error:

```
Traceback (most recent call last):
  File "/media/stian/hgst6tb/OneDrive/DUS/PhD/All_Neis/Representative_genomes/MELD/meld/MELD-DNA-Zenodo/P1-General-Binding/input-files/setupMELD.py", line 9, in <module>
    from meld.system.restraints import LinearRamp,ConstantRamp
ImportError: cannot import name 'LinearRamp' from 'meld.system.restraints' (/home/stian/miniconda3/envs/my-meld-project/lib/python3.9/site-packages/meld/system/restraints.py)
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
```

**Comment by GoldEagle93** [comment]
Hello Stianale,

The error you are getting is most likely due having a newer version of MELD compared to when those scripts were generated. See if the problem exists with simple protein systems. I'll try to reproduce the script with newer versions and update in the coming days. I'll also try to post an updated walkthrough.

Reza

**Comment by stianale** [comment]
Thanks. I tried the simple protein script in getting_started.rst, but get this error:

`Traceback (most recent call last):
  File "/media/stian/hgst6tb/OneDrive/DUS/PhD/All_Neis/Representative_genomes/meld/test_setup.py", line 13, in <module>
    builder = system.AmberSystemBuilder(build_options)
NameError: name 'system' is not defined
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------`

**Comment by GoldEagle93** [comment]
It sounds like a mismatch but these errors are out of my expertise. I'd wait for MELD developers to take care of this case.

**Comment by jlmaccal** [comment]
Yes, the last version of MELD with a conda release is 0.6.1. Cutting on a new release is on the list of things to do, but finding time is difficult.

**Comment by stianale** [comment]
Do you know which version of MELD was used in the original MELD-DNA publication?

I do not have GPUs, nor access to any HPC cluster. I read that MELD-DNA needs 30 GPUs, running for perhaps two days. That sounds extensive. Maybe there is a way to use all my 16 CPU cores, speeding it up somewhat, or maybe running MELD-DNA locally is just not feasible?

**Comment by GoldEagle93** [comment]
I think it was 0.4.19.

The reason we use 30 GPUs is that MELD runs replica exchange, so one simulation on each GPU. While I don't think you will be able to run any significant amount on CPU, even if you could, you will be limited to 16 replicas which might not be enough depending on your system of interest.

**Comment by stianale** [comment]
Thanks for the helpful answers.

I can't envision getting access to 30 GPUs even on a cluster, sounds excessive. I understand it is necessary for the exhaustive molecular dynamics, but due to this is very hard to replicate for others. Maybe the scripts could benefit from a rewrite. For GROMACS, for example, I am able to run up to 70 nanoseconds of protein-DNA complexes in a day on my desktop that does not even have GPUs.

**Comment by stianale** [comment]
Hello again,

Maybe I misunderstood the GPU requirement... is it 30 GPU cores or strictly speaking 30 GPUs that are needed?

**Comment by GoldEagle93** [comment]
It is around 30 separate GPUs that are needed (each GPU has thousands of cores). The exact number of GPUs required depends on the system size and how you set up the replica exchanging system but most of what we do is fine with 30.

**Comment by alberto99** [comment]
hi,
You should also be able to run the different number of replicas in 1 GPU. if you want to run 30 replicas, it will take 30 times longer than running a 30 GPU job. 
Best,

**Comment by stianale** [comment]
> hi, You should also be able to run the different number of replicas in 1 GPU. if you want to run 30 replicas, it will take 30 times longer than running a 30 GPU job. Best,

Sorry for the late reply.

That could take about 2 months. According to the MELD-DNA paper, jobs running on 30 GPUs usually need about 2 days.

I only have my RTX 4090. I don't have access to a cluster. The way MELD-DNA works as of now and the code, running it seems like an extremely strenuous task in any case (who is granted access to 30 GPUs on cluster anyway?). 

The MELD code as of the current state of this repo is also far from compatible with MELD-DNA. :/
