### ISSUE TITLE
Exception: Encountered NaN when evaluating collections.

### ISSUE THREAD

**Issue by he-leon** [maccallumlab/meld#22]
Hello!

I'm trying to reproduce the results from your paper "Accelerating molecular simulations of proteins using
Bayesian inference on weak information". 
Alberto already gave me some hints via E-Mail on how to launch MELD simulations. However in a lot of cases simulations will fail right after starting them. Whether the simulation will run seems to dependent on the input sequence, structure and the chosen restraints and their parameters.
The system seems to "blow up" in a lot of cases. 
As a test sequence I use 1POU from the PDB, which was also used in the paper.
I'm using the script heuristics.py form the Examples Directory as a basis. I only made some small adjustments regarding sequence and 2ndary structure input. For my first attempt i decided to only use secondary structure restraints. The other restraints are commented out. Here is the code:

```python
#!/usr/bin/env python
# encoding: utf-8

from __future__ import print_function
import numpy as np
from meld.remd import ladder, adaptor, master_runner
from meld import system
from meld import comm, vault
from meld import parse
from meld.system.restraints import LinearRamp

N_REPLICAS = 30
N_STEPS = 10000
BLOCK_SIZE = 100

hydrophobes = 'AILMFPWV'
hydrophobes_res = ['ALA', 'ILE', 'LEU', 'MET', 'PHE', 'PRO', 'TRP', 'VAL']

def make_ss_groups(secondary, subset=None): # 2ndary structure supplied as argument 
    active = 0
    extended = 0
    sse = []
    # ss = open('ss.dat', 'r').readlines()[0]
    for i, l in enumerate(secondary.rstrip()):
        print(i, l)
        if l not in "HE.":
            continue
        if l not in 'E' and extended:
            end = i
            sse.append((start + 1, end))
            extended = 0
        if l in 'E':
            if i+1 in subset:
                active = active + 1
            if extended:
                continue
            else:
                start = i
                extended = 1
    print(active)
    return(sse, active)

def generate_strand_pairs(s, sse, active, subset=None):
#no change

def make_pairNO(g,s,i,j):
#no change

def make_pairON(g,s,i,j):
#no change

def create_hydrophobes(s,ContactsPerHydroph=1.3,scaler=None,group_1=np.array([]),group_2=np.array([])):
#no change


def gen_state(s, index):
    pos = s._coordinates
    pos = pos - np.mean(pos, axis=0)
    vel = np.zeros_like(pos)
    alpha = index / (N_REPLICAS - 1.0)
    energy = 0
    # Had to add a box vector here as system.SystemState requires i as an argument
    box_vec = [.0, .0, .0] 
    return system.SystemState(pos, vel, alpha, energy, box_vec)


def get_dist_restraints(filename, s, scaler):
  #no change


def setup_system():
    # load the sequence
    #sequence = parse.get_sequence_from_AA1(filename='sequence.dat')
    # 1POU
   seq_str="DLEELEQFAKTFKQRRIKLGFTQGDVGLAMGKLYGNDFSQTTISRFEALNLSFKNMCKLKPLLEKWLNDAE"
    sequence = parse.get_sequence_from_AA1(contents=seq_str)
    n_res = len(sequence.split())

    # build the system
    p = system.ProteinMoleculeFromSequence(sequence)
    b = system.SystemBuilder()
    s = b.build_system_from_molecules([p])
    s.temperature_scaler = system.GeometricTemperatureScaler(0, 0.4, 300., 550.)

    #
    # Secondary Structure
    #
    ss_scaler = s.restraints.create_scaler('constant')
    secondary=".HHHHHHHHHHHHHHHHH....HHHHHHHHHHHH.....HHHHHHHH.....HHHHHHHH"
    ss_rests = parse.get_secondary_structure_restraints(contents=secondary, system=s, scaler=ss_scaler,   
                    torsion_force_constant=2.5, distance_force_constant=2.5)
    n_ss_keep = int(len(ss_rests) * 0.70)  
    s.restraints.add_selectively_active_collection(ss_rests, n_ss_keep)

    #
    # Confinement Restraints
    #
    conf_scaler = s.restraints.create_scaler('constant')
    confinement_rests = []
    confinement_dist = (16.9*np.log(s.residue_numbers[-1])-15.8)/28.
    for index in range(n_res):
        rest = s.restraints.create_restraint('confine', conf_scaler, LinearRamp(0,100,0,1),res_index=index+1, atom_name='CA', radius=confinement_dist, force_const=250.0)
        confinement_rests.append(rest)
    s.restraints.add_as_always_active_list(confinement_rests)

    #
    # Distance Restraints
    #
    # High reliability
    #
    #dist_scaler = s.restraints.create_scaler('nonlinear', alpha_min=0.4, alpha_max=1.0, factor=4.0)
    #contact80_dist = get_dist_restraints('target_contacts_over_80.dat', s, dist_scaler)
    #n_high_keep = int(0.80 * len(contact80_dist))
    #s.restraints.add_selectively_active_collection(contact80_dist, n_high_keep)

    #
    # Long
    #
    #contact60_dist = get_dist_restraints('target_contacts_over_60.dat', s, dist_scaler)
    #n_high_keep = int(0.60 * len(contact60_dist))
    #s.restraints.add_selectively_active_collection(contact60_dist, n_high_keep)

    #
    # Heuristic Restraints
    #
    #subset= np.array(range(n_res)) + 1

        #
        # Hydrophobic
        #
    #create_hydrophobes(s,scaler=dist_scaler,group_1=subset)

        #
        # Strand Pairing
        #
#    sse,active = make_ss_groups(secondary, subset=subset)
    #generate_strand_pairs(s,sse,active,subset=subset)


    # create the options
    options = system.RunOptions()
    options.implicit_solvent_model = 'gbNeck2'
    options.use_big_timestep = True
    options.cutoff = 1.8

    options.use_amap = True
    options.amap_beta_bias = 1.0
    options.timesteps = 14286
    options.minimize_steps = 20000

    # create a store
    store = vault.DataStore(s.n_atoms, N_REPLICAS, s.get_pdb_writer(), block_size=BLOCK_SIZE)
    store.initialize(mode='w')
    store.save_system(s)
    store.save_run_options(options)

    # create and store the remd_runner
    l = ladder.NearestNeighborLadder(n_trials=48 * 48)
    policy = adaptor.AdaptationPolicy(2.0, 50, 50)
    a = adaptor.EqualAcceptanceAdaptor(n_replicas=N_REPLICAS, adaptation_policy=policy)

    remd_runner = master_runner.MasterReplicaExchangeRunner(N_REPLICAS, max_steps=N_STEPS, ladder=l, adaptor=a)
    store.save_remd_runner(remd_runner)

    # create and store the communicator
    c = comm.MPICommunicator(s.n_atoms, N_REPLICAS)
    store.save_communicator(c)

    # create and save the initial states
    states = [gen_state(s, i) for i in range(N_REPLICAS)]
    store.save_states(states, 0)

    # save data_store
    store.save_data_store()

    return s.n_atoms


setup_system()
```

Generation of the system and the initial states works without problems. 

I use launch_remd_multiplex to start the simulation. It fails right after executing it throwing the following Exception:
```
Traceback (most recent call last):
  File "/usr/bin/launch_remd_multiplex", line 4, in <module>
    __import__('pkg_resources').run_script('Meld==0.2.4', 'launch_remd_multiplex')
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 744, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1499, in run_script
    exec(code, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/Meld-0.2.4-py2.7.egg/EGG-INFO/scripts/launch_remd_multiplex", line 26, in <module>
    main()
  File "/usr/lib/python2.7/site-packages/Meld-0.2.4-py2.7.egg/EGG-INFO/scripts/launch_remd_multiplex", line 22, in main
    launch.launch_multiplex(console, args.debug)
  File "/usr/lib/python2.7/site-packages/Meld-0.2.4-py2.7.egg/meld/remd/launch.py", line 148, in launch_multiplex
    runner.run(system_runner, store)
  File "/usr/lib/python2.7/site-packages/Meld-0.2.4-py2.7.egg/meld/remd/multiplex_runner.py", line 91, in run
    states[state_index])
  File "/usr/lib/python2.7/site-packages/Meld-0.2.4-py2.7.egg/meld/util.py", line 39, in wrapper
    res = func(*args, **kwds)
  File "/usr/lib/python2.7/site-packages/Meld-0.2.4-py2.7.egg/meld/system/openmm_runner/runner.py", line 83, in minimize_then_run
    return self._run(state, minimize=True)
  File "/usr/lib/python2.7/site-packages/Meld-0.2.4-py2.7.egg/meld/system/openmm_runner/runner.py", line 275, in _run
    self._simulation.step(self._options.timesteps)
  File "/usr/lib/python2.7/site-packages/simtk/openmm/app/simulation.py", line 133, in step
    self._simulate(endStep=self.currentStep+steps)
  File "/usr/lib/python2.7/site-packages/simtk/openmm/app/simulation.py", line 203, in _simulate
    self.integrator.step(10) # Only take 10 steps at a time, to give Python more chances to respond to a control-c.
  File "/usr/lib/python2.7/site-packages/simtk/openmm/openmm.py", line 11906, in step
    return _openmm.LangevinIntegrator_step(self, steps)
Exception: Encountered NaN when evaluating collections.
```

Adjusting either  torsion_force_constant=2.5 and distance_force_constant=2.5 to very small values (eg. 0.01) or reducing the enforced percentage of restraints to values like 10% will make the simulation work. However, i guess using such low values is just like not applying restraints at all.

Can you help me with this issue? My Trial and Error approaches by adjusting the parameters didn't result in any success. I'm using AMBER12 with AMBER12SB. Using AMBER16 and AMBER14SB ( (with amap=false) force-field results in the same error. 

Thanks! 

Best regards 
Leonhard

**Comment by jlmaccal** [comment]
Hi Leonhard,

This is a common error that we encounter. It arises due to a combination of:
1. Bad geometry produced by tleap, especially when certain residues precede proline.
2. Force constants that are initially too high.
3. The minimizer in OpenMM not always being able to do much with a bad initial structure.

There are two things you should try, probably in combination.

First, you can add a `Ramp` (most likely a `LinearRamp`) to all of your restraints. This will slowly turn on the restraints over the first part of your simulation. You have one above for the confinement restraints, which scales the restraints from zero to full strength over the first 100 steps. You should also add one for the secondary structures using the `ramp=` parameter of `parse.get_secondary_structure_restraints`.

Second, we have very rudimentary support for MonteCarlo moves that can often resolve bad geometry involving prolines.

You would need to do something like the following:
```python
movers = []
for i in range(1, n_res + 1):
    n = s.index_of_atom(i, 'N') - 1
    ca = s.index_of_atom(i, 'CA') - 1
    c = s.index_of_atom(i, 'C') - 1

    mover = meld.system.montecarlo.DoubleTorsionMover(
        n, ca, list(range(ca, n_atoms),
        ca, c, list(rane(c, n_atoms))
    movers.append((mover, 1.0))
scheduler = meld.system.monecarlo.MonteCarloScheduler(movers, n_res * 60)

options.min_mc = scheduler                                               
```

I might have screwed that up a bit, but the idea should be correct. Basically, you create a bunch of `Mover` objects that know how to make a MC move. You assign weights, all 1.0 in this case. You then pass these to a scheduler which will do a certain number of trails (`n_res * 60`) randomly making a weighted choice of mover for each trial. You then tell MELD that you want to use these movers during minimization.

In my experience, that should be able to resolve all of the bad clashes and you shouldn't have problems at startup anymore. Note that the MC is: (1) obviously not fully developed, and (2) really slow.

**Comment by he-leon** [comment]
Using a ramp works! Thank you for you help!
