### ISSUE TITLE
Conda install meld failure.

### ISSUE THREAD

**Issue by jcminerlanl** [maccallumlab/meld#30]
Hello,

Having recently installed conda and making sure to source it properly so that all dependencies are invoked, the following results are occurring as a function of the two commands
$ conda config --add channels omnia
$ conda install meld 

Fetching package metadata ...........

PackageNotFoundError: Package missing in current osx-64 channels: 
  - meld

Close matches found; did you mean one of these?

    meld: meld3

Is there a reason why conda is unable to identify meld? Is there a new name by which conda would identify it?

**Comment by jlmaccal** [comment]
Ah sorry, some of that documentation is a bit out of date.

The current best way to get `meld` is:
```
conda install -c omnia -c maccallum_lab meld-cuda75
```
or `meld-cuda80` depending on your cuda version.

Note that you will also need to uninstall `openmm` if you have it installed, as these meld packages will pull in `openmm-cuda75` or -openmm-cuda80` from the `maccallum_lab` channel.

**Comment by jcminerlanl** [comment]
That seemed to do the trick at first:

meld jcminer$ conda install -c omnia -c maccallum_lab meld-cuda75
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment /Users/jcminer/anaconda2:

The following NEW packages will be INSTALLED:

    ambermini:     16.16.0-7         omnia        
    fftw3f:        3.3.4-2           omnia        
    hdf4:          4.2.11-0                       
    libgcc:        4.8.5-1                        
    libnetcdf:     4.4.1-0                        
    meld-cuda75:   0.3.12-py27_0     maccallum_lab
    mock:          2.0.0-py27_0                   
    mpi4py:        2.0.0-py27_0                   
    netcdf4:       1.2.4-np111py27_1              
    openmm-cuda75: 7.1.0-py27_0      maccallum_lab
    openmpi:       1.6.3-1                        
    pbr:           1.10.0-py27_0                  

The following packages will be UPDATED:

    anaconda:      4.3.1-np111py27_0               --> custom-py27_0

The following packages will be DOWNGRADED due to dependency conflicts:

    curl:          7.52.1-0                        --> 7.49.0-1     
    pycurl:        7.43.0-py27_2                   --> 7.43.0-py27_0

Proceed ([y]/n)? y

fftw3f-3.3.4-2 100% |###############################################################################| Time: 0:00:00   2.62 MB/s
libgcc-4.8.5-1 100% |###############################################################################| Time: 0:00:00   3.14 MB/s
openmpi-1.6.3- 100% |###############################################################################| Time: 0:00:00   9.27 MB/s
ambermini-16.1 100% |###############################################################################| Time: 0:00:02   9.86 MB/s
curl-7.49.0-1. 100% |###############################################################################| Time: 0:00:00   8.17 MB/s
hdf4-4.2.11-0. 100% |###############################################################################| Time: 0:00:00  12.65 MB/s
anaconda-custo 100% |###############################################################################| Time: 0:00:00   1.04 MB/s
libnetcdf-4.4. 100% |###############################################################################| Time: 0:00:00  10.20 MB/s
mpi4py-2.0.0-p 100% |###############################################################################| Time: 0:00:00  12.78 MB/s
openmm-cuda75- 100% |###############################################################################| Time: 0:00:00   8.46 MB/s
pycurl-7.43.0- 100% |###############################################################################| Time: 0:00:00   8.58 MB/s
netcdf4-1.2.4- 100% |###############################################################################| Time: 0:00:00  10.55 MB/s
pbr-1.10.0-py2 100% |###############################################################################| Time: 0:00:00   8.25 MB/s
mock-2.0.0-py2 100% |###############################################################################| Time: 0:00:00  14.07 MB/s
meld-cuda75-0. 100% |###############################################################################| Time: 0:00:00  12.74 MB/s


However, after the install, I attempted to run some tests in the directory: ./meld/meld/slow_tests/real_remd
The following errors were produced.

real_remd jcminer$ nosetests
E
======================================================================
ERROR: Failure: ImportError (dlopen(/Users/jcminer/anaconda2/lib/python2.7/site-packages/netCDF4/_netCDF4.so, 2): Library not loaded: @rpath/libmfhdf.0.dylib
  Referenced from: /Users/jcminer/anaconda2/lib/libnetcdf.11.dylib
  Reason: image not found)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jcminer/anaconda2/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/jcminer/anaconda2/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/jcminer/anaconda2/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/jcminer/meld/meld/slow_tests/real_remd/test_real_remd.py", line 12, in <module>
    from meld import comm, vault
  File "/Users/jcminer/anaconda2/lib/python2.7/site-packages/meld/vault.py", line 11, in <module>
    import netCDF4 as cdf
  File "/Users/jcminer/anaconda2/lib/python2.7/site-packages/netCDF4/__init__.py", line 3, in <module>
    from ._netCDF4 import *
ImportError: dlopen(/Users/jcminer/anaconda2/lib/python2.7/site-packages/netCDF4/_netCDF4.so, 2): Library not loaded: @rpath/libmfhdf.0.dylib
  Referenced from: /Users/jcminer/anaconda2/lib/libnetcdf.11.dylib
  Reason: image not found

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)


The anaconda library being referenced exists, and my .bashrc reads:
export PATH="/Users/jcminer/anaconda2/bin:..."
I even ran python setup.py install in the main meld/ directory after the failure and got the same results.

What is meld missing that is needed to identify this directory?

**Comment by jlmaccal** [comment]
I'm not sure... this looks like more of a problem with the netcdf install. This looks suspicious to me: `Library not loaded: .0.dylib`.
