### ISSUE TITLE
MPI_Abort

### ISSUE THREAD

**Issue by ever4cyth** [maccallumlab/meld#32]
Please help with the following error. Is it because I run launch_remd on my desktop (i7)? but I can run a 8 processes MPI job on my desktop like mpirun -np 8 sander.MPI -O -i heat3.in -p TC5b.prmtop -c heat2.rst -r heat3.rst -o heat3.out -x heat3.mdcrd

Thanks!

launch_remd --debug
loading data store
initializing communicator
Traceback (most recent call last):
  File "/home/mango/python/bin/launch_remd", line 4, in <module>
    __import__('pkg_resources').run_script('Meld==0.3.12', 'launch_remd')
  File "/home/mango/python/lib/python2.7/site-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/mango/python/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1500, in run_script
    exec(code, namespace, namespace)
  File "/home/mango/python/lib/python2.7/site-packages/Meld-0.3.12-py2.7.egg/EGG-INFO/scripts/launch_remd", line 29, in <module>
    main()
  File "/home/mango/python/lib/python2.7/site-packages/Meld-0.3.12-py2.7.egg/EGG-INFO/scripts/launch_remd", line 25, in main
    launch.launch(console, args.debug, args.console_log)
  File "/home/mango/python/lib/python2.7/site-packages/Meld-0.3.12-py2.7.egg/meld/remd/launch.py", line 61, in launch
    communicator.broadcast_logger_address_to_slaves(logger_address)
  File "/home/mango/python/lib/python2.7/site-packages/Meld-0.3.12-py2.7.egg/meld/util.py", line 39, in wrapper
    res = func(*args, **kwds)
  File "/home/mango/python/lib/python2.7/site-packages/Meld-0.3.12-py2.7.egg/meld/comm.py", line 118, in broadcast_logger_address_to_slaves
    self._timeout_message.format('broadcast_logger_address_to_slaves'))):
KeyError: 'func_name'
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1
:
system msg for write_line failure : Bad file descriptor

**Comment by ever4cyth** [comment]
Thanks for your reply! I downloaded the new version and tried. It gave a different error.

  File "/home/mango/python/lib/python2.7/site-packages/Meld-0.3.12-py2.7.egg/meld/util.py", line 39, in wrapper
    res = func(*args, **kwds)
  File "/home/mango/python/lib/python2.7/site-packages/Meld-0.3.12-py2.7.egg/meld/comm.py", line 106, in broadcast_alphas_to_slaves
    self._mpi_comm.scatter(alphas, root=0)
  File "MPI/Comm.pyx", line 1286, in mpi4py.MPI.Comm.scatter (src/mpi4py.MPI.c:109079)
  File "MPI/msgpickle.pxi", line 707, in mpi4py.MPI.PyMPI_scatter (src/mpi4py.MPI.c:48114)
  File "MPI/msgpickle.pxi", line 161, in mpi4py.MPI.Pickle.dumpv (src/mpi4py.MPI.c:41605)
ValueError: expecting 1 items, got 8
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1
:
system msg for write_line failure : Bad file descriptor
