### ISSUE TITLE
multicore?

### ISSUE THREAD

**Issue by ever4cyth** [maccallumlab/meld#34]
Dear Justin,

Is it possible MELD can be modified to run on multicore computer using mpirun -np? I don't have computer cluster so I tried mpirun but got the following error. Could you please help? Thanks!

Traceback (most recent call last):
  File "/home/mango/python/bin/launch_remd", line 4, in <module>
    __import__('pkg_resources').run_script('Meld==0.3.12', 'launch_remd')
  File "/home/mango/python/lib/python2.7/site-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/mango/python/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1500, in run_script
    exec(code, namespace, namespace)
  File "/home/mango/python/lib/python2.7/site-packages/Meld-0.3.12-py2.7.egg/EGG-INFO/scripts/launch_remd", line 29, in <module>
    main()
  File "/home/mango/python/lib/python2.7/site-packages/Meld-0.3.12-py2.7.egg/EGG-INFO/scripts/launch_remd", line 25, in main
    launch.launch(console, args.debug, args.console_log)
  File "/home/mango/python/lib/python2.7/site-packages/Meld-0.3.12-py2.7.egg/meld/remd/launch.py", line 104, in launch
    remd_runner.run(communicator, system_runner)
  File "/home/mango/python/lib/python2.7/site-packages/Meld-0.3.12-py2.7.egg/meld/remd/slave_runner.py", line 59, in run
    system_runner.prepare_for_timestep(my_alpha, self._step)
  File "/home/mango/python/lib/python2.7/site-packages/Meld-0.3.12-py2.7.egg/meld/system/openmm_runner/runner.py", line 83, in prepare_for_timestep
    self._initialize_simulation()
  File "/home/mango/python/lib/python2.7/site-packages/Meld-0.3.12-py2.7.egg/meld/system/openmm_runner/runner.py", line 195, in _initialize_simulation
    prmtop.topology, sys, self._integrator, platform, properties)
  File "/home/mango/python/lib/python2.7/site-packages/Meld-0.3.12-py2.7.egg/meld/system/openmm_runner/runner.py", line 329, in _create_openmm_simulation
    return Simulation(topology, system, integrator, platform, properties)
  File "/home/mango/python/lib/python2.7/site-packages/simtk/openmm/app/simulation.py", line 105, in __init__
    self.context = mm.Context(self.system, self.integrator, platform, platformProperties)
  File "/home/mango/python/lib/python2.7/site-packages/simtk/openmm/openmm.py", line 9811, in __init__
    this = _openmm.new_Context(*args)
Exception: Illegal value for DeviceIndex: 1
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 1

**Comment by jlmaccal** [comment]
The options for running MELD are currently to use `launch_remd`, which requires one gpu per core, or to use `launch_remd_multiplex`, which can only use a single gpu and single core.
