### ISSUE TITLE
MELD 0.4.7 not restartable from 0.4.6 runs

### ISSUE THREAD

**Issue by cing** [maccallumlab/meld#58]
Not a huge deal  because one should just not mix versions of any MD software in the middle of a simulation as a guiding principle in life, but it's worth mentioning somewhere. You get a traceback like this when you try to do it. I suspect this was not meant to be a backwards incompatible change, so it's possible that better defaults may help but it's low priority.

```
Traceback (most recent call last):
  File "/home/ceing/meld-dev3.6/bin//launch_remd", line 4, in <module>
    __import__('pkg_resources').run_script('Meld==0.4.7', 'launch_remd')
  File "/home/ceing/meld-dev3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 657, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/ceing/meld-dev3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1437, in run_script
    exec(code, namespace, namespace)
  File "/home/ceing/meld-dev3.6/lib/python3.6/site-packages/Meld-0.4.7-py3.6.egg/EGG-INFO/scripts/launch_remd", line 29, in <module>
    main()
  File "/home/ceing/meld-dev3.6/lib/python3.6/site-packages/Meld-0.4.7-py3.6.egg/EGG-INFO/scripts/launch_remd", line 25, in main
    launch.launch(console, args.debug, args.console_log)
  File "/home/ceing/meld-dev3.6/lib/python3.6/site-packages/Meld-0.4.7-py3.6.egg/meld/remd/launch.py", line 108, in launch
    remd_runner.run(communicator, system_runner, store)
  File "/home/ceing/meld-dev3.6/lib/python3.6/site-packages/Meld-0.4.7-py3.6.egg/meld/remd/master_runner.py", line 116, in run
    system_runner.prepare_for_timestep(0., self._step)
  File "/home/ceing/meld-dev3.6/lib/python3.6/site-packages/Meld-0.4.7-py3.6.egg/meld/system/openmm_runner/runner.py", line 112, in prepare_for_timestep
    self._initialize_simulation()
  File "/home/ceing/meld-dev3.6/lib/python3.6/site-packages/Meld-0.4.7-py3.6.egg/meld/system/openmm_runner/runner.py", line 193, in _initialize_simulation
    self._options.implicitSolventSaltConc,
  File "/home/ceing/meld-dev3.6/lib/python3.6/site-packages/Meld-0.4.7-py3.6.egg/meld/system/system.py", line 576, in implicitSolventSaltConc
    return self._implicitSolventSaltConc
AttributeError: 'RunOptions' object has no attribute '_implicitSolventSaltConc'
```

**Comment by jlmaccal** [comment]
This is less than ideal, but it creates a huge amount of code bloat to make sure things like this work across versions. For now, I'm inclined to leave things as they are.
