### ISSUE TITLE
Launch REMD error (platform error)

### ISSUE THREAD

**Issue by zhenglz** [maccallumlab/meld#67]
Here are the three platforms that work with openmm

`python -m simtk.testInstallation`
`There are 3 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces
3 OpenCL - Successfully computed forces

Median difference in forces between platforms:

Reference vs. CPU: 1.97786e-05
Reference vs. OpenCL: 2.15121e-05
CPU vs. OpenCL: 1.55399e-05`

When I tried to launch a remd simulation using "launch_remd", I got the following error:

`loading data store
initializing communicator
/home/lzheng002/.conda/envs/md/lib/python3.6/site-packages/simtk/openmm/app/internal/amber_file_parser.py:1017: UserWarning: Non-optimal GB parameters detected for GB model GBn2
  'Non-optimal GB parameters detected for GB model %s' % gbmodel)
Traceback (most recent call last):
  File "/home/lzheng002/.conda/envs/md/bin/launch_remd", line 4, in <module>
    __import__('pkg_resources').run_script('Meld==0.4.14', 'launch_remd')
  File "/home/lzheng002/.conda/envs/md/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/lzheng002/.conda/envs/md/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1453, in run_script
    exec(code, namespace, namespace)
  File "/home/lzheng002/.conda/envs/md/lib/python3.6/site-packages/Meld-0.4.14-py3.6.egg-info/scripts/launch_remd", line 29, in <module>
    main()
  File "/home/lzheng002/.conda/envs/md/lib/python3.6/site-packages/Meld-0.4.14-py3.6.egg-info/scripts/launch_remd", line 25, in main
    launch.launch(console, args.debug, args.console_log)
  File "/home/lzheng002/.conda/envs/md/lib/python3.6/site-packages/meld/remd/launch.py", line 108, in launch
    remd_runner.run(communicator, system_runner, store)
  File "/home/lzheng002/.conda/envs/md/lib/python3.6/site-packages/meld/remd/master_runner.py", line 116, in run
    system_runner.prepare_for_timestep(0., self._step)
  File "/home/lzheng002/.conda/envs/md/lib/python3.6/site-packages/meld/system/openmm_runner/runner.py", line 112, in prepare_for_timestep
    self._initialize_simulation()
  File "/home/lzheng002/.conda/envs/md/lib/python3.6/site-packages/meld/system/openmm_runner/runner.py", line 240, in _initialize_simulation
    platform = Platform.getPlatformByName("CUDA")
  File "/home/lzheng002/.conda/envs/md/lib/python3.6/site-packages/simtk/openmm/openmm.py", line 16025, in getPlatformByName
    return _openmm.Platform_getPlatformByName(name)
Exception: There is no registered Platform called "CUDA"
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1
:
system msg for write_line failure : Bad file descriptor`

Please indicate how to solve the problem. Thanks!

**Comment by cing** [comment]
Thanks for getting started with MELD. Unfortunately, MELD requires the use of the CUDA kernel and cannot be run on Reference/CPU/OpenCL platforms. You need to find a machine with NVIDIA GPUs and install OpenMM there. Once you do that an additional platform will be available, and then you should be able to run `launch_remd` without the error above. Let us know if there are any additional problems regarding the platform and we can reopen this issue.
